apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 313440846714.dkr.ecr.us-east-1.amazonaws.com/ecr_repo
        ports:
        - containerPort: 8000
